name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚧 Set up project
        run: pnpm dev:prepare

      - name: 🛠️ Build project
        run: pnpm prepack

      - name: ✅ Lint
        run: pnpm lint

      # - name: 🧪 Test project
      #   run: pnpm test
